### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by arararar** [theleadio/corona-frontend#8]
Good morning Dear Sir! 
I wonder if its possible to provide a longterm graph of the infections on the website, i cant still decide „by eye“ if its developing linear or still exponential. (?)
It would be helpful if the ratio „todays total:yesterdays total“ could be included or even further an additional diagram, containing the first and second derivative. (?)
Thank you very much for your precious work!

**Comment by xming13** [comment]
Hi @arararar, there is daily trend chart on the website now :)
e.g. for Malaysia: https://www.coronatracker.com/country/my/
